name: deploy
description: Build and deploy

inputs:
  env:
    description: 'The environment'
    required: true
  site_url:
    description: ''
    required: true
  cms_url:
    description: ''
    required: true
  strapi_token:
    description: ''
    required: true
  storage_account:
    description: ''
    required: true
  cdn_endpoint:
    description: ''
    required: true
  cdn_profile:
    description: ''
    required: true
  resource_group:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Login
      id: login
      # from https://github.com/Azure/login/commits/master
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Use Node.js
      id: nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Build
      id: build
      shell: bash
      env:
        SITE_URL: ${{ input.site_url }}
        STRAPI_TOKEN: ${{ inputs.strapi_token }}
        STRAPI_API_URL: ${{ inputs.cms_url }}
      run: |
        yarn install
        yarn build
    - name: Azure upload
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          # Empty storage
          az storage blob delete-batch \
            --account-name ${{ input.storage_account }} \
            --source '$web'

          # Upload to storage
          az storage blob upload-batch \
            --account-name ${{ input.storage_account }} \
            --source public \
            --destination '$web' \
            --overwrite

          # Purge CDN
          az cdn endpoint purge \
            --name ${{ input.cdn_endpoint }} \
            --profile-name ${{ input.cdn_profile }} \
            --resource-group ${{ input.resource_group }} \
            --content-paths '/*'
